# Use official Python image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy files into container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port for Web App
EXPOSE 7860

# Run the web application
CMD ["python", "colorize_webapp.py"]
